name: Milestone Created

on:
  milestone:
    types: [created]

jobs:
  create-issue-and-trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check milestone title
        id: check_milestone
        run: |
          if [[ "${{ github.event.milestone.title }}" == *"2.0"* ]]; then
            echo "Milestone contains 2.0"
            echo "::set-output name=contains_2_0::true"
          else
            echo "Milestone does not contain 2.0"
            echo "::set-output name=contains_2_0::false"
            exit 0
          fi

      - name: Create issue
        if: steps.check_milestone.outputs.contains_2_0 == 'true'
        run: |
          gh issue create \
          --title "Really?" \
          --body "Naaaahhh" \
          --milestone ${{ github.event.milestone.number }}
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Trigger Close Milestone
        if: steps.check_milestone.outputs.contains_2_0 == 'true'
        run: |
          gh api repos/${{ github.repository }}/dispatches \
            -X POST \
            -F event_type=close-milestone \
            -F client_payload='{"milestone_number":${{ github.event.milestone.number }}}' \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"
        env:
          GH_TOKEN: ${{ github.token }}