name: 5b. Close Milestone

on:
  repository_dispatch:
    types: [close-milestone]

jobs:
  close-milestone:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Close milestone
        run: |
          gh api \
            -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/${{ github.repository }}/milestones/${{ github.event.client_payload.milestone_number }} \
            -F state="closed"

            # Get the list of issues associated with the milestone
            ISSUES=$(gh api \
              -H "Accept: application/vnd.github.v3+json" \
              /repos/${{ github.repository }}/issues?milestone=${{ github.event.client_payload.milestone_number }}\&state=open \
          --jq '.[].number')

            # Close each issue associated with the milestone
            for ISSUE in $ISSUES; do
              gh api \
                -X PATCH \
                -H "Accept: application/vnd.github.v3+json" \
                /repos/${{ github.repository }}/issues/$ISSUE \
                -F state="closed"
            done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}