name: Backup to S3

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */5 * *' # Runs at midnight every 5 days

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region ap-southeast-5

    - name: Create backup archive
      run: |
        TIMESTAMP=$(date +'%Y%m%d%H%M%S')
        zip -r backup-$TIMESTAMP.zip .

    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        TIMESTAMP=$(date +'%Y%m%d%H%M%S')
        aws s3 cp backup-$TIMESTAMP.zip s3://github-actions-demo-asyrique/backup-$TIMESTAMP.zip